language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql LANG=de; MW=master
      php: 5.3
    - env: DBTYPE=sqlite LANG=de; MW=master
      php: 5.3
    - env: DBTYPE=sqlite LANG=de; MW=master
      php: 5.4
    - env: DBTYPE=mysql LANG=de; MW=master
      php: 5.4
    - env: DBTYPE=mysql LANG=en; MW=master
      php: 5.5
    - env: DBTYPE=sqlite LANG=en; MW=master
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
      - abraham.taherivand@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
