language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"

env:
  matrix:
    - LANG=de DBTYPE=sqlite MW=master
    - LANG=en DBTYPE=mysql MW=master

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
      - abraham.taherivand@wikimedia.de
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
