version: '2'

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: wmde/data-bridge-node
    volumes:
      - '~/.npm:/.npm'
      - './../..:/app:ro' # grant read access to allow e.g. jest watch to detect changes
      - '.:/app/client/data-bridge'
    working_dir: /app/client/data-bridge
    environment:
      - NODE_ENV
      - NODE_DEBUG
      - DEBUG

  csr:
    extends:
      service: node
    ports:
      - '${CSR_PORT}:8080'
    command: 'npm run-script serve'
