version: '2'

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: wmde/data-bridge-node
    volumes:
      - '~/.npm:/.npm'
      - './:/app'
      - './../../.git:/app/.git:ro' # allows jest-watch-typeahead to detect changes
    working_dir: /app
    environment:
      - NODE_ENV
      - NODE_DEBUG
      - DEBUG

  csr:
    extends:
      service: node
    ports:
      - '${CSR_PORT}:8080'
    command: 'npm run-script serve'
